##
## EPITECH PROJECT, 2019
## Visual Studio Live Share (Workspace)
## File description:
## Makefile
##

NAME	=	IMAGECOMPRESSOR
DIRINSTALL	:=	$(shell stack path --local-install-root)/bin/imageCompressor


all:	$(NAME)

$(NAME):
	@cp $(DIRINSTALL) ../.

.PHONY:	all